# Generated by Django 3.0.5 on 2020-04-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('author', models.CharField(max_length=100)),
                ('datePublished', models.DateField()),
                ('numberOfPages', models.IntegerField()),
                ('typeOfBook', models.CharField(choices=[('ON', 'One of Novel'), ('DC', 'Documentation'), ('Ot', 'Other')], default='ON', max_length=2)),
            ],
        ),
    ]
