# Generated by Django 3.0.5 on 2020-04-12 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book_Form_CRUD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='typeOfBook',
            field=models.CharField(choices=[('One of Novel', 'One of Novel'), ('Documentation', 'Documentation'), ('Other', 'Other')], default='One of Novel', max_length=15),
        ),
    ]
